### ISSUE TITLE
 camera white artefacts

### ISSUE THREAD

**Issue by Flauschi1981** [geekydoc/android_device_l70pn#47]
the camera app has white artefacts and i can not save the pictures and i cant boot in recovery mode                                                                                        ! plz fix it

Not working even with the "cm13.0-20161111-UNOFFICIAL"

**Comment by geekydoc** [comment]
There is a patch on the xda forums thread which will fix the white artefacts for you. The device should save pictures normally, this issue has been fixed in an early update. Try cleaning up the ART cache and the cache partition and if the issue persists, you have to provide us with an android log while you take a picture.

For entering recovery mode, open a terminal app, become superuser and issue the command:" reboot recovery " . If the device does not boot into recovery, there is something wrong with the recovery image. The rom does not have to do with that, nor changes anything on the recovery partition when installed.

**Comment by Flauschi1981** [comment]
ok thx but how i install the patch? with TWRP? and sry but how i clean the art cache? sry ^^

greetings

**Comment by geekydoc** [comment]
Yes, install it through twrp

**Comment by Flauschi1981** [comment]
ok it works BIG thx :)
