### ISSUE TITLE
Tellefon issues

### ISSUE THREAD

**Issue by Flauschi1981** [geekydoc/android_device_l70pn#50]
cm13.0-20161206-UNOFFICIAL

when i make a telefon conversation the display goes off and i cant hang out because the display is off. after the interlocutor hang out than i can use the telefon normal. all other works fine plz help

(sry for my bad english)

greetings

**Comment by geekydoc** [comment]
This is most probably due to the increase in the range of the proximity sensor which is introduced in the last release. The sensor will detect everything in a distance of 10cm. While on a phone call, the screen automatically turns off when the sensor detects something. Make sure you get the phone far enough from you, so the screen will turn on and you can hang the phone. This behavior of the screen be disabled completely in the Dialer  application settings.

**Comment by Flauschi1981** [comment]
no it dont work! but with cm14.1-20161205-UNOFFICIAL it workt 100 procent!
